#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-hsqldb
Version  : 2.3.4
Release  : 1
URL      : https://github.com/ryenus/hsqldb/archive/2.3.4.tar.gz
Source0  : https://github.com/ryenus/hsqldb/archive/2.3.4.tar.gz
Source1  : https://repo1.maven.org/maven2/org/hsqldb/hsqldb/2.3.4/hsqldb-2.3.4.jar
Source2  : https://repo1.maven.org/maven2/org/hsqldb/hsqldb/2.3.4/hsqldb-2.3.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-hsqldb-data = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : buildreq-mvn

%description
Readme File
2016/05/15-15:20:30
This package contains HyperSQL v. 2.3.4
HyperSQL Database is a relational database management system and a set of tools
written in Java.
HyperSQL is also known as HSQLDB.

%package data
Summary: data components for the mvn-hsqldb package.
Group: Data

%description data
data components for the mvn-hsqldb package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/hsqldb/hsqldb/2.3.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/hsqldb/hsqldb/2.3.4/hsqldb-2.3.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/hsqldb/hsqldb/2.3.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/hsqldb/hsqldb/2.3.4/hsqldb-2.3.4.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/hsqldb/hsqldb/2.3.4/hsqldb-2.3.4.jar
/usr/share/java/.m2/repository/org/hsqldb/hsqldb/2.3.4/hsqldb-2.3.4.pom
